[package]
name = "testing-rust"
version = "0.1.0"
authors = ["Maxim"]
edition = "2018"

[dependencies]
image = "0.21"
vulkano = "0.13.0"
vulkano-shaders = "0.13.0"
vulkano-win = "0.13"
winit = "0.19"
